CREATE DATABASE IF NOT EXISTS webweavr_recon;

USE webweavr_recon;

CREATE TABLE IF NOT EXISTS scans (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  ip         VARCHAR(45)  NOT NULL,
  domain     VARCHAR(255) NOT NULL,
  status     VARCHAR(50)  NOT NULL,
  scanned_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
